<template>
  <div class="about article">
    <h1>Why and who is doing this?</h1>
    <h3><strong>TL;DR:</strong> My name is Colin, I am interested in brain computer interface and built this website to help share the knowledge with everyone else.</h3>
    <p>Four years ago while working on an electronics-based art project, I experienced a new feeling for the first time. The feeling was a sense of amazement as my mind opened to all new possibilities, as I realized the impossible was possible. So often, we limit our thinking to what we have seen as possible before. Through my experience with this art project, I found that innovation comes when you consider the impossible and think outside the box. Let me explain...</p>
		<p>I was working on a project for a local art show. The show tasked exhibitors to create a piece that combined nature with technology creating something “synthetically natural”. While bouncing ideas off each other, the topic of capacitive touch came up. That's the technology that makes your smartphone screen touchable and swipeable. I was informed that it was possible to build your own sensors with simple electronic components and that you could implant the sensors in organic materials and detect when a human touches the material. I figured it would be amazingly difficult to learn and apply this technology in such a short time and create something acceptable for the art show.  Nevertheless, I set out to build a prototype.</p>
		<p>After ordering and assembling a circuit of parts I had little to no experience with, I planted the sensor into the soil of an aloe plant. I fired up the controller and then proceeded to touch the aloe plant. To an onlooker it may have been a bit anticlimactic, but for me, as I touched the aloe, I watched a series of numbers fly by on a nearby computer screen, representing readings from the sensor.  As I touched the leaves, the values would quickly change, and they would even change as I slid my finger along the leaves. I was elated! It worked, and it was performing better than I had imagined. What seemed impossible was now possible! Even though capacitive touch had already been invented, it was like I was inventing it for the first time. By going through the process of building the sensors with my own hands, I gained knowledge of the essential building blocks. Once the circuit was built and working, I had a flood of ideas regarding possible uses for both my sensor and the knowledge of how it was built. Still to this day, I find myself applying what I learned on this art project towards future projects.</p>
		<p>Beyond the success of building a touch sensor for plants, I look back on this experience as a pivotal moment in my life. I had the realization that I was limiting myself. Preconceived notions of what was difficult or out of my scope of capabilities was keeping me from trying something new. I have always been a bit curious, but this experience unlocked my curiosity to learn more so that I could apply knowledge towards other problems and goals. After the capacitive touch project, I started another project, this time involving EEG sensors. By hacking a readily-available toy used to monitor brain wave rhythms, I was able to reprogram the toy to visually paint a portrait of an individual's mental activities. What had led me to EEG was how similar an EEG sensor is to a capacitive touch sensor-both are sensing electrical properties at a distance. With this technology, I was able to peer inside an individual’s brain! Ultimately, I yearned for more knowledge and found myself back in school. Studying Cognitive Science at UCSD, I am learning about the inner workings of the brain. My goal is to apply this knowledge towards improving brain computer interfaces (BCIs). With the growth of machine learning, advancements in pattern recognition are fueling better BCIs. I hope to be a part of this growing field and help make the impossible possible.</p>
  </div>
</template>
